services:
  - type: web
    region: frankfurt
    name: strapi
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /
    disk:
      name: Strapi Source
      mountPath: /opt/render/project/src/public/uploads
      sizeGB: 10
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: v12.18.3
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_HOST
        fromDatabase:
          name: strapidb
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: strapidb
          property: port
      - key: DATABASE_USERNAME
        fromDatabase:
          name: strapidb
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: strapidb
          property: password
      - key: DATABASE_NAME
        fromDatabase:
          name: strapidb
          property: database
      - key: ADMIN_JWT_SECRET
        sync: false
databases:
  - name: strapidb
    databaseName: strapi
    user: strapi
    region: frankfurt
